apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      environment: staging
    includeSelectors: true

replicas:
  - name: promptledger-api
    count: 2

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml

images:
  - name: promptledger/demo
    newName: ghcr.io/hamzakhan7473/promptledger
    newTag: staging
